codingBear01/cosmost_fe

src/components/ui/SignUpForm/SignUpForm.jsx
기능 수정
feature/UserRegisterAPI -> develop
회원가입 유효성 검사 출력 수정. 입력값이 빈 값인 경우에는 유효성 검사 결과를 사용자에게 표시하지 않음
정상
=> 회원가입 유효성 검사 출력 수정

src/App.js, src/components/ui/CourseDetailForm/CourseDetailForm.jsx, src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx, src/components/ui/SearchedCoursesForm/SearchedCoursesForm.jsx, src/components/ui/SignUpForm/SignUpForm.jsx, src/store/function.js, src/store/index.js
#7 [update] 프로파일 이미지 바이너리 데이터로 변환 가능하도록 수정
기능 업데이트
프로파일 이미지 바이너리 데이터로 변환 가능하도록 수정
- #7
=> #7 [update] 프로파일 이미지 바이너리 데이터로 변환 가능하도록 수정

src/App.js, src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx, src/components/ui/CourseDetailForm/CourseDetailForm.jsx, src/components/ui/CourseDetailForm/CourseImageCarousel/CourseImageCarousel.jsx, src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/CourseSharingAndLikeButton.jsx, src/components/ui/CourseDetailForm/CourseTitleAndDate/CourseTitleAndDate.jsx, src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx, src/store/function.js, src/store/index.js
기능 추가
코스 상세페이지의 네이버 지도 구현, 사용자 정보 API 일부 구현
- #3
=> 코스 상세페이지 대부분의 API 구현

src/App.js, src/components/common/DeleteModal/DeleteModal.jsx, src/components/common/Header/HeaderUtilBtn/HeaderUtilBtn.jsx, src/components/index.js, src/components/pages/NotFoundPage.jsx, src/components/pages/Rankers.jsx, src/components/pages/index.js, src/components/ui/CourseDetailForm/CourseDetailForm.jsx, src/components/ui/CourseDetailForm/CourseImageCarousel/CourseImageCarousel.jsx, src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/CourseSharingAndLikeButton.jsx, src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx, src/components/ui/CoursesForm/Course/Course.jsx, src/components/ui/CoursesForm/CoursesForm.jsx, src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx, src/components/ui/InputEmailForm/InputEmailForm.jsx, src/components/ui/InputUserForm/InputUserForm.jsx, src/components/ui/LoginForm/LoginForm.jsx, src/components/ui/RankersForm/RankersForm.jsx, src/components/ui/RankersForm/index.js, src/components/ui/RankersForm/styled.js, src/components/ui/UserPageForm/UserPageForm.jsx, src/components/ui/index.js, src/store/function.js, src/store/temporaryArray/MainCourses.js
기능 추가
- 코스 조회 무한 스크롤 기능 구현
- #16
=> Done: 코스 조회 무한 스크롤 기능 구현

src/components/ui/InputEmailForm/InputEmailForm.jsx
기능 수정
- 비밀번호 찾기 이메일 인증 폼에서 주석 해제
=> Done: 비밀번호 입력 폼 주석 해제

src/components/common/Header/Header.jsx, src/components/common/Header/HeaderSearchBar/HeaderSearchBar.jsx, src/components/common/MenuListForm/MenuListForm.jsx, src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx, src/components/ui/CourseDetailForm/CourseDetailForm.jsx, src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx, src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/CourseSharingAndLikeButton.jsx, src/components/ui/CourseDetailForm/CourseTitleAndDate/styled.js, src/components/ui/CoursesForm/CoursesForm.jsx, src/components/ui/CoursesForm/SelectingCategoryArea/SelectingCategoryArea.jsx, src/store/functions.js
기능 추가, 코드 수정
- 코스 리뷰 좋아요 등록 및 취소 기능 구현
- 코스 상세 조회 평점 퍼센테이지 관련 코드 수정
- 헤더 키워드 서치바에서 서치 버튼 클릭 시 검색되도록 수정
- params.type을 활용하여 코스 조회용 url 바뀌도록 수정
- #3 
- #5
=> Done: 코스 리뷰 좋아요 구현, 키워드 검색 기능 및 코스 조회용 url 관련 코드 수정

src/components/common/DeleteModal/DeleteModal.jsx, src/components/common/Header/HeaderUtilBtn/HeaderUtilBtn.jsx, src/components/common/HistoriesForm/HistoriesForm.jsx, src/components/common/ReportForm/ReportForm.jsx, src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx, src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/CourseSharingAndLikeButton.jsx, src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx, src/components/ui/CoursesForm/CoursesForm.jsx, src/components/ui/CoursesForm/SelectingCategoryArea/SelectingCategoryArea.jsx, src/components/ui/InputEmailForm/InputEmailForm.jsx, src/components/ui/InputUserForm/InputUserForm.jsx, src/components/ui/LoginForm/LoginForm.jsx, src/components/ui/WithdrawUserForm/WithdrawUserForm.jsx, src/store/functions.js
=> Done: 배포용 api 환경변수로 수정

src/apis/api.js, src/components/common/Header/HeaderUtilBtn/HeaderUtilBtn.jsx, src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx, src/components/ui/CourseDetailForm/CourseDetailForm.jsx, src/components/ui/CoursesForm/Course/Course.jsx, src/components/ui/CoursesForm/CoursesForm.jsx, src/components/ui/InputEmailForm/InputEmailForm.jsx
버그 수정
코스 조회 API 버그 수정 
로그인 시 토큰이 삭제되는 버그 수정
- #5 
- #6
=> #5 [update] 코스 조회 API 버그 수정 및 로그인 시 토큰이 삭제되는 버그 수정

public/index.html, src/App.js, src/apis/api.js, src/components/common/MenuListForm/MenuListForm.jsx, src/components/pages/FindingUserPage.jsx, src/components/pages/InputPassword.jsx, src/components/pages/WithdrawUser.jsx, src/components/ui/CoursesForm/CoursesForm.jsx, src/components/ui/DaumAddressApiForm/DaumAddressApiForm.jsx, src/components/ui/DisplayFindedIdForm/DisplayFindedIdForm.jsx, src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx, src/components/ui/InputEmailForm/InputEmailForm.jsx, src/components/ui/InputPasswordForm/InputPasswordForm.jsx, src/components/ui/InputUserForm/InputUserForm.jsx, src/components/ui/LoginForm/LoginForm.jsx, src/components/ui/MainSection/MainSection.jsx, src/components/ui/WithdrawUserForm/WithdrawUserForm.jsx
기능 추가
회원 정보 수정 API 일부 구현
- #6 
- #35
=> #35 [create] 회원 정보 수정 API 구현 및 네이버 로그인 API 일부 구현

src/components/ui/LoginForm/LoginForm.jsx
브랜치 병합
- feature/Courses branch와 develop branch와 병합
=> Done: merge feature/Courses with develop branch

src/components/common/OrderingModal/OrderingModal.jsx, src/components/ui/CoursesForm/CoursesForm.jsx
버그 수정
메인페이지에서 코스명 입력해서 검색할 시 코스가 뜨지 않는 버그 수정
[코스 검색 버그 전면 수정]
- #5
=> #5 코스 검색 버그 전면 수정

src/apis/api.js, src/apis/index.js, src/components/common/HistoriesForm/HistoriesForm.jsx, src/components/common/ReportForm/ReportForm.jsx, src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx, src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx, src/components/ui/CourseDetailForm/CourseReviewRegisterForm/CourseReviewRegisterForm.jsx, src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/CourseSharingAndLikeButton.jsx, src/components/ui/CourseDetailForm/CourseTitleAndDate/CourseTitleAndDate.jsx, src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx, src/components/ui/DaumAddressApiForm/DaumAddressApiForm.jsx, src/components/ui/FollowsForm/FollowListItem/FollowListItem.jsx, src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx, src/components/ui/InputEmailForm/InputEmailForm.jsx, src/components/ui/InputPasswordForm/InputPasswordForm.jsx, src/components/ui/InputUserForm/InputUserForm.jsx, src/components/ui/LoginForm/LoginForm.jsx, src/components/ui/WithdrawUserForm/WithdrawUserForm.jsx
버그 수정
- token 따로 빼놔서 api에 입력이 되지 않던 버그 수정
=> [update] api token 수정

src/components/ui/CoursesForm/CoursesForm.jsx
=> #5 [update] 코스 검색 정렬 전환 버그 수정 

src/components/ui/CoursesForm/CoursesForm.jsx, src/components/ui/InputEmailForm/InputEmailForm.jsx
=> Fix: 이메일 입력폼에 네이버 이메일 확인 정규식 추가

src/components/ui/CoursesForm/CoursesForm.jsx
=> Done: 해시태그 검색 수정

src/apis/api.js, src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx, src/components/ui/CourseDetailForm/CourseDetailForm.jsx, src/components/ui/DisplayFindedIdForm/DisplayFindedIdForm.jsx
버그 수정
- 코스 리뷰 없을 시 코스 상세 조회 시 평균 평점 ui 수정
- 아이디 찾기를 통해 찾은 아이디 전체 보여주기
=> Fix: 코스 상세 조회 시 평균 평점 ui, 아이디 찾기 전체 보여주기 수정

src/apis/api.js, src/apis/index.js, src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx, src/components/ui/CourseDetailForm/CourseDetailForm.jsx, src/components/ui/CoursesForm/CoursesForm.jsx, src/components/ui/FollowsForm/FollowListItem/FollowListItem.jsx, src/components/ui/FollowsForm/FollowsForm.jsx, src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx, src/components/ui/InputPasswordForm/InputPasswordForm.jsx, src/components/ui/InputUserForm/InputUserForm.jsx, src/components/ui/UserPageForm/UserPageForm.jsx, src/components/ui/UserPageForm/UserProfilArea/UserProfilArea.jsx, src/components/ui/UserPageForm/UserProfilArea/styled.js
기능 추가, 버그 수정
- 마이 페이지 나의 팔로워, 팔로잉 수 조회
- 마이 페이지 팔로우 조회 관련 로직 수정
- 코스 상세 조회 페이지에서 팔로우/언팔로우
- 코스 작성자 팔로워 수 및 팔로워 조회
=> Fix: 팔로우 기능 수정

src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
=> #3 [update] 코스 등록 시 마크 표시되게 수정

package.json
=> #4 [update] 코스 등록 마커 표시 버그 수정2

src/components/common/OrderingModal/OrderingModal.jsx, src/components/ui/CoursesForm/CoursesForm.jsx, src/store/MainCourses.js
ui 수정
- 검색 타입 메시지 추가 등 코스 검색 및 정렬 관련 ui 수정
=> Done: 코스 검색 및 정렬 ui 수정

src/App.js, src/components/pages/Messages.jsx, src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx, src/components/ui/CourseDetailForm/CourseDetailForm.jsx, src/components/ui/CourseDetailForm/CourseTitleAndDate/CourseTitleAndDate.jsx, src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx, src/components/ui/CourseRegistrationForm/styled.js, src/components/ui/CoursesForm/Course/Course.jsx, src/components/ui/CoursesForm/CoursesForm.jsx, src/components/ui/FollowsForm/FollowListItem/FollowListItem.jsx, src/components/ui/FollowsForm/FollowsForm.jsx, src/components/ui/InputEmailForm/InputEmailForm.jsx, src/components/ui/LoginForm/LoginForm.jsx, src/store/functions.js
버그 수정
- 중복 이메일 메시지 처리
- 에러, 404 페이지 메인으로 redirect
- 코스 등록 시 미리보기 이미지 스타일 수정
- 팔로우 버튼 안 보이게 수정
=> Done: UI 및 버그 수정

src/apis/api.js, src/components/ui/CourseDetailForm/CourseDetailForm.jsx, src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx, src/components/ui/CoursesForm/CoursesForm.jsx
버그 수정
- 코스 수정 시 기존 정보 중복 입력되는 현상 수정
=> Done: 코스 수정 버그 수정 작업

src/App.js, src/components/ui/LoginForm/LoginForm.jsx
버그 수정
- token을 활용한 route 분기 처리 수정
=> Done: Route token 분기 처리 수정

src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx, src/components/ui/CoursesForm/Course/Course.jsx, src/store/functions.js
코드 수정
- 코스 상세 조회 네이버 지도 주석 해제
- 코스 리뷰 개수 조회 안 되면 0으로 표시
=> Done: 코스 상세 조회 네이버 지도 주석 해제, 코스 리뷰 개수 조회 안 되면 0으로 표시

src/App.js, src/components/ui/CourseDetailForm/CourseDetailForm.jsx, src/components/ui/CoursesForm/Course/Course.jsx
=> Fix: Route 분기 시 token 활용

src/App.js, src/components/ui/LoginForm/LoginForm.jsx, src/components/ui/UserPageForm/UserPageForm.jsx
버그수정
로그인 토큰 관리 및 정보 수정된 닉네임 반영 버그 수정
- #6
=> [update] 로그인 토큰 관리 및 정보 수정된 닉네임 반영 버그 수정

src/App.js, src/apis/api.js, src/apis/index.js, src/components/common/Header/HeaderUtilBtn/HeaderUtilBtn.jsx, src/components/common/MenuListForm/MenuListForm.jsx, src/components/common/PageContainer/PageContainer.jsx, src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx, src/components/ui/CourseDetailForm/CourseDetailForm.jsx, src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx, src/components/ui/FollowsForm/FollowListItem/FollowListItem.jsx, src/components/ui/FollowsForm/FollowsForm.jsx, src/components/ui/InputEmailForm/InputEmailForm.jsx, src/components/ui/InputPasswordForm/InputPasswordForm.jsx, src/components/ui/LoginForm/LoginForm.jsx, src/components/ui/UserInformationForm/UserInformationForm.jsx, src/components/ui/UserPageForm/UserPageForm.jsx, src/components/ui/UserPageForm/UserProfilArea/UserProfilArea.jsx, src/store/index.js, src/store/recoilStates.js
=> Fix: 이메일 관련 기능 수정

src/apis/api.js, src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx, src/components/ui/CourseDetailForm/CourseContentWrap/styled.js, src/components/ui/CourseDetailForm/CourseDetailForm.jsx, src/components/ui/CoursesForm/Course/Course.jsx, src/components/ui/CoursesForm/Course/styled.js, src/components/ui/CoursesForm/CoursesForm.jsx
=> Fix: 코스 순서 관련 ui 수정

src/components/ui/CourseDetailForm/CourseDetailForm.jsx
=> Fix: 장소 한줄평 스타일 수정

src/components/ui/InputEmailForm/InputEmailForm.jsx
=> [update] 이메일 변경 버그 수정

src/apis/api.js, src/components/ui/InputEmailForm/InputEmailForm.jsx, src/components/ui/UserPageForm/UserProfilArea/UserProfilArea.jsx
버그 수정
회원 관련 버그 수정
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
=> [update] 회원 관련 버그 수정

src/apis/api.js, src/components/pages/FindingUserPage.jsx, src/components/ui/DisplayFindedIdForm/DisplayFindedIdForm.jsx, src/components/ui/FollowsForm/FollowListItem/FollowListItem.jsx, src/components/ui/FollowsForm/FollowListItem/styled.js, src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx, src/components/ui/InputEmailForm/InputEmailForm.jsx, src/components/ui/InputPasswordForm/InputPasswordForm.jsx
버그 수정
- 아이디 및 비밀번호 찾기 관련 버그 수정
=> Fix: 아이디 및 비밀번호 찾기 버그 수정

src/apis/api.js, src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx, src/components/ui/InputEmailForm/InputEmailForm.jsx
[update] 주소 변경 이슈 해결
버그 수정
주소 변경 이슈 해결
=> [update] 주소 변경 이슈 해결

src/components/common/ReportForm/ReportForm.jsx, src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx, src/components/ui/CourseDetailForm/CourseReviewRegisterForm/CourseReviewRegisterForm.jsx, src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx, src/components/ui/InputEmailForm/InputEmailForm.jsx, src/components/ui/InputPasswordForm/InputPasswordForm.jsx, src/components/ui/InputUserForm/InputUserForm.jsx, src/components/ui/LoginForm/LoginForm.jsx, src/components/ui/WithdrawUserForm/WithdrawUserForm.jsx
코드 수정
- 검증 관련 toast error를 warn으로 수정
=> Done: toast error를 warn으로 수정

src/apis/api.js, src/apis/index.js, src/components/common/ReportForm/ReportForm.jsx, src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx, src/components/ui/CourseDetailForm/CourseDetailForm.jsx, src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx, src/components/ui/CoursesForm/Course/Course.jsx, src/components/ui/CoursesForm/Course/styled.js, src/components/ui/CoursesForm/SelectingCategoryArea/SelectingCategoryArea.jsx, src/components/ui/FollowsForm/FollowListItem/FollowListItem.jsx
UI 수정
- 코스 순서 ui 및 네이버 마커 ui 수정
=> Done: 코스 순서 UI 및 네이버 마커 UI 수정

src/components/ui/CoursesForm/Course/Course.jsx, src/components/ui/CoursesForm/Course/styled.js
=> Done: 코스 조회 ui 수정

src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx
=> [update] 회원가입 이메일 분기 처리 완료

src/components/common/PageContainer/PageContainer.jsx, src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx, src/components/ui/CourseRegistrationForm/styled.js, src/components/ui/CoursesForm/Course/Course.jsx
UI 및 버그 수정
- 코스 등록 인풋 폰트 사이즈 수정
- 코스 제목 글자수 수정
- 마이페이지 메뉴 navigate 분기 처리
=> Done: 코스 등록 인풋 폰트 사이즈 수정, 코스 제목 글자수 수정, 마이페이지 메뉴 navigate 분기 처리

src/apis/api.js, src/components/common/HistoriesForm/HistoryListItem/HistoryListItem.jsx
버그 수정
- 내가 남긴 리뷰 조회에서 코스 제목 조회
=> Done: 내가 남긴 리뷰 조회에서 코스 제목 조회

src/components/ui/CoursesForm/Course/Course.jsx
=> Done: 코스 제목 글자 수 스타일 수정

src/App.js, src/components/ui/CoursesForm/CoursesForm.jsx
기능 추가
- 내가 작성한 코스 및 좋아요 페이지에 데이터가 없을 시 메시지 출력, 푸터 없애기
=> Done: 내가 작성한 코스 및 좋아요 한 코스 분기 처리

src/components/ui/CoursesForm/CoursesForm.jsx
=> Done: 마이 페이지 코스 조회 분기 처리 수정

src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx, src/components/ui/CoursesForm/Course/Course.jsx, src/components/ui/CoursesForm/CoursesForm.jsx
=> Done: placeOrder 숫자 삭제

src/components/ui/CoursesForm/CoursesForm.jsx
버그 수정
- 해시태그 및 키워드 검색 결과 메시지 수정
=> Done: 해시태그 및 키워드 검색 결과 메시지 수정

src/apis/api.js, src/apis/index.js, src/components/common/Header/HeaderUtilBtn/HeaderUtilBtn.jsx, src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx, src/components/ui/CourseDetailForm/CourseReviewRegisterForm/CourseReviewRegisterForm.jsx, src/components/ui/CoursesForm/CoursesForm.jsx, src/components/ui/InputEmailForm/InputEmailForm.jsx, src/components/ui/UserPageForm/UserPageForm.jsx
=> Done: api 분리 리팩토링

src/components/ui/CourseDetailForm/CourseImageCarousel/CourseImageCarousel.jsx, src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx, src/store/functions.js
=> Done: imgUrl 수정

src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/CourseSharingAndLikeButton.jsx
=> Done: url 복사 수정

src/components/ui/CourseDetailForm/CourseDetailForm.jsx
=> Done: 네이버 지도 마커 ui 수정

src/components/ui/CourseDetailForm/CourseDetailForm.jsx
=> Done: 상세 조회 코스 마커 ui 수정
